### ISSUE TITLE
Powershell Core doesn't seem to  support Get-WinSystemLocale

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/WELA-deprecated#38]
```
./WELA.ps1
Get-WinSystemLocale: /Users/user/Documents/YamatoSecurity/WELA/WELA.ps1:202:17
Line |
 202 |  $HostLanguage = Get-WinSystemLocale | Select-Object Name # en-US, ja- …
     |                  ~~~~~~~~~~~~~~~~~~~
     | The term 'Get-WinSystemLocale' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included,
     | verify that the path is correct and try again.
```
Powershell CoreはGet-WinSystemLocaleに対応していないようです。

**Comment by YamatoSecurity** [comment]
<img width="1127" alt="Screen Shot 2021-09-09 at 19 45 19" src="https://user-images.githubusercontent.com/71482215/132672430-7121c2c5-0cab-4634-bc46-7d8e15e63f81.png">
<img width="1124" alt="Screen Shot 2021-09-09 at 19 44 49" src="https://user-images.githubusercontent.com/71482215/132672439-d81a216f-b972-4266-8881-d0cc0a6272cb.png">

PowershellCoreでは使えないですね。。

**Comment by hitenkoku** [comment]
Get-WinSystemLocaleの代わりにGet-HostのCurrentCultureが使えます。
どちらかというとLinuxやMacなどでevtxファイルを指定するGet-WinEventが使えない状態があまりよろしくないです
(APIがWindows用にしか開かれてない)

- Powershell Core

> PS > (get-host).CurrentCulture
> 
> LCID             Name             DisplayName
> ----             ----             -----------
> 1033             en-US            English (United States)
> 

- Powershell 5.1

> PS > (get-host).CurrentCulture
> 
> LCID             Name             DisplayName
> ----             ----             -----------
> 1041             ja-JP            日本語 (日本)

**Comment by hitenkoku** [comment]
Get-WinEventが以下の[issue](https://github.com/PowerShell/PowerShell/issues/5810)でもある通りWindows専用なので、Powershellでevtxを読み込むための外部モジュールが必要になります。

**Comment by YamatoSecurity** [comment]
残念・・とりあえず、Powershell Coreの対応をやめましょう・・
Since Powershell Core does not support viewing windows event logs we are dropping support for now..
