### ISSUE TITLE
Add APT-Hunter Logon feature

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/WELA-deprecated#47]
APT-Hunterの攻撃検知ルールを追加する。

- [ ] APT-Hunterのロジックを確認する
- [ ] WELAへと攻撃検知ルールの移植を行う

DeepBlueCLIのイベントログを用いて同様の結果が得られるようにする。

**Comment by YamatoSecurity** [comment]
<img width="596" alt="Logon-SuccessFail" src="https://user-images.githubusercontent.com/71482215/137444893-89cb616f-b94b-4e9f-8000-34f5ece9a62f.png">
こんな感じですが、更にログオンに成功したタイプによって分けたい（例：2 Interactive等々）のと、失敗したログオンを２種類に分けたいです→Bad User Failed Logon (ユーザ名が存在しないから失敗した）とBad Password Failed Logon (パスワードが間違ったから失敗した)
カラムはBad User Failed Logins | Bad Password Failed Logins:  | Type 0 (System) Logins: | Type 2 (Interactive) Logins | 等々という感じで

**Comment by ghost** [comment]
ログオンの成功タイプおよび失敗したログオンの種類ごとに認証イベント（4624, 4625）をカウントする機能のプロトタイプを作成してみました。
添付させて出力内容でイメージ合いますでしょうか？
![image](https://user-images.githubusercontent.com/59769602/145854204-ab72fc4d-0f81-419f-86a7-f56d7f91bd98.png)

**Comment by YamatoSecurity** [comment]
@oginoPmP 
ありがとうございます！
よく考えたら4625のログオンに失敗したログにもTypeがあるので、それもリストアップしたいのですが、横が相当広くなってしまうので、4つのリストに分けたいと思います。
イメージは以下の通りです：

```
Successful Logons:
User  | Type 0 (System) | Type 1 (xxx) | Type 2 (xxx) | 等々
IEUser | 0 | 1 | 0 | 等々

Failed Logons (Wrong Password):
User  | Type 0 (System) | Type 1 (xxx) | Type 2 (xxx) | 等々
IEUser | 0 | 1 | 0 | 等々

Failed Logons (Non-existent User):
User  | Type 0 (System) | Type 1 (xxx) | Type 2 (xxx) | 等々
IEUser | 0 | 1 | 0 | 等々

Failed Logons (Other reason):
User  | Type 0 (System) | Type 1 (xxx) | Type 2 (xxx) | 等々
IEUser | 0 | 1 | 0 | 等々
```

(※タイプは番号だけでは分かりにくいので、xxxの代わりにタイプ名も書きたいです）

これをお願いできますか？

**Comment by hitenkoku** [comment]
内容を見たところ他issueで記載している内容とかぶっているので #73 も @oginoPmP さんに提案してもらった形で対応してもらえれば完了となる認識です。#73のタスクの方にduplicate labelをつけておきました

**Comment by YamatoSecurity** [comment]
あ、ごめんなさい。色々勘違いしてしまいました。
上記の形で大丈夫です！ありがとうございます！
