### ISSUE TITLE
Logon Timeline Bug: セキュリティ以外のタイムラインが作成されてしまう

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/WELA-deprecated#58]
ログオンタイムラインはセキュリティログのみなので、他のログで解析しても意味がないので、セキュリティログだけにしたいです。
<img width="770" alt="WELA-bug-logon timeline on other logs" src="https://user-images.githubusercontent.com/71482215/137446281-69124eba-2051-4c83-902f-07e521aa8238.png">

とりあえず端末一台のログのタイムラインができたらOKです。いつか複数対応にしたいのですが、ロジックが複雑になりそうです。そんなに難しくないかな？例えばレスポンダーが複数の端末からwindowsイベントログディレクトリをまるごと収集してきて、全部一気に処理して別々のタイムラインファイルに保存したい場合。（標準出力でも対応しても良いけど、情報が多いので実際は.csvに保存することが多いかな。その場合は再帰的に.evtxを確認して、Channelが"Security"かどうかを最初のログエントリで確認して、セキュリティログだったらタイムラインを作成して、<Computer>.evtxという別々のファイルに保存すると、後でTimeline Explorer等で解析できます。

とりあえずセキュリティログだけ処理するように直すのをお願いできますか？

**Comment by hitenkoku** [comment]
https://github.com/Yamato-Security/WELA/commits/hitenkoku/issue58 で対象の個所の修正が完了しましたのでPullRequestを出しておきました。また、LogFile及びLogDirectoryオプションのチェックでStringのはずがBoolとして扱われていた個所があったため同時に修正をしておきました。

LiveAnalysis指定時にLogonTimeLineを実行したらSecurity.evtxのみを取得するようには変更をしておきました
LiveAnalysisを指定せずにLogDirectoryもしくはLogFileで指定をした時には通常通り読み込む扱いとしています(他マシンからevtxファイルを回収してまとめて修正をしたい場合の時を想定しています)
