### ISSUE TITLE
-EventIDStatistics not present (as per examples)

### ISSUE THREAD

**Issue by sailingbikeruk** [Yamato-Security/WELA-deprecated#79]
In the ReadMeEnglish.md file the first example is:

 ./WELA.ps1 -LogFile .\Security.evtx -EventIDStatistics

This returns no output and on inspection of the code it appears that there is no parameter that equals -EventIDStatistics. There is one specifically for security -SecurityEventID_Statistics events.

It seems that more than one of the parameters have changed. -LogonTimeline is alos now -SecurityLogonTimeline.

Can you correct the examples in the readme files please.

**Comment by hitenkoku** [comment]
@sailingbikeruk I have checked. You are right. "-SecurityEventID_Statistics" is correct.

I will fix the ReadmeEnglish.md .

Thank you for your comment.
