### ISSUE TITLE
the util.ps1  is virus file?

### ISSUE THREAD

**Issue by MaxFate233** [Yamato-Security/WELA-deprecated#80]
![image](https://user-images.githubusercontent.com/28295403/147575547-3c529fbc-67e1-4ce9-85e5-d903e9db6776.png)

**Comment by hitenkoku** [comment]
@huangrihan  Thanks comment.
I Checked detected function.
[Check-Command](https://github.com/Yamato-Security/WELA/blob/main/Config/util.ps1#L212-L276) function is detected.

This function is same logic [DeepBlue CLI](https://github.com/sans-blue-team/DeepBlueCLI) and WELA.

I think the heuristics probably detected the Base64 decoding part and so on.
Please check the target source code and use the OSS at your own risk.

**Comment by hitenkoku** [comment]
@huangrihan  You haven't replied for a week, has the issue been resolved? If not, please ReOpen the issue and comment!
