### ISSUE TITLE
Error when reading huge size evtx files

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/WELA-deprecated#94]
refs https://github.com/Yamato-Security/WELA/discussions/93

**Comment by hitenkoku** [comment]
@YamatoSecurity  こちらの方でトータル6GBのログを動かしてみましたが同様のエラーは出てきませんでした。そちらのほうで大容量のデータとかで問題が再現するか確認してもらってもよろしいでしょうか。

**Comment by YamatoSecurity** [comment]
@hitenkoku 了解です。後で試してみます。

**Comment by YamatoSecurity** [comment]
I think this was fixed in https://github.com/Yamato-Security/WELA/pull/99
Can we close this?
